name: PRL (test-2)
on: 
  pull_request_target: 
    types: [opened, synchronize, reopened, closed]
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4 # Uploads repository content to the runner
      with:
        sparse-checkout: |
          .github
    - uses: actions/labeler@v5
      with:
        sync-labels: false
        dot: true