name: Labeler Issue 841
on: 
  pull_request: 
    types: [opened, synchronize, reopened, closed]
  push:

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4 # Uploads repository content to the runner
      with:
        sparse-checkout: |
          .github
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: '.github/labeler.yml'
        sync-labels: true