# name: PRL (test-1)
# on: 
#   pull_request_target: 
#     types: [opened, synchronize, reopened, closed]
#name: Labeler Issue 775
# on: 
#   pull_request_target: 
#     types: [opened, reopened, closed]

# jobs:
#   label:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       pull-requests: write

#     steps:
#     - uses: actions/checkout@v4 # Uploads repository content to the runner
#       with:
#         sparse-checkout: |
#           .github
#     - uses: actions/labeler@v5
#       with:

#         sync-labels: true
#         dot: true
name: issue 775
on:
  pull_request:
    types: [ closed ]
jobs:
  delete_channel:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: チェックアウト
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - id: pr_labels
        uses: actions/labeler@v5

