name: Labeler
on: 
  pull_request_target: 
    types: [ opened, synchronize, reopened, closed]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        with: '.github/labeler.yml'
        sync-labels: true
        pr-number: 2