name: Labeler
on: 
  pull_request_target: 
    types: [ opened, synchronize, reopened, closed]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4 # Uploads repository content to the runner
      with:
        repository: "suyashgaonkar/labeler-demo"
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: '.github/labeler.yml'
        sync-labels: true
        pr-number: 2